#!/bin/bash

# Install & enable appmode
pip install appmode
jupyter nbextension     enable --py --sys-prefix appmode
jupyter serverextension enable --py --sys-prefix appmode

# Import the workspace into JupyterLab
# jupyter lab workspaces import binder/workspace.json
